import os
import base64
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types

from src.state import State

# img_generator.py lives at: Blog-Writing-Agent/reducer/img_generator.py
# so parent.parent gets us back to the repo root regardless of CWD.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Load .env from the project root explicitly (don't rely on CWD for this either)
load_dotenv(PROJECT_ROOT / ".env")

IMAGES_DIR = PROJECT_ROOT / "images"
BLOG_DIR = PROJECT_ROOT / "blogs"


def _gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires: pip install google-genai python-dotenv
    Env var: GEMINI_API_KEY (loaded from Blog-Writing-Agent/.env)
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY is not set (check Blog-Writing-Agent/.env)."
        )

    client = genai.Client(api_key=api_key)

    resp = client.models.generate_content(
        model="gemini-3.1-flash-lite-image",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["TEXT", "IMAGE"],
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_ONLY_HIGH",
                )
            ],
        ),
    )

    parts = getattr(resp, "parts", None)
    if not parts and getattr(resp, "candidates", None):
        try:
            parts = resp.candidates[0].content.parts
        except Exception:
            parts = None

    if not parts:
        raise RuntimeError("No image content returned (safety/quota/SDK change).")

    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            data = inline.data
            # Some SDK versions return base64-encoded str instead of raw bytes
            if isinstance(data, str):
                data = base64.b64decode(data)
            return data

    raise RuntimeError("No inline image bytes found in response.")


def generate_and_place_images(state: State) -> dict:
    plan = state["plan"]
    assert plan is not None

    md = state.get("md_with_placeholders") or state["merged_md"]
    image_specs = state.get("image_specs", []) or []

    BLOG_DIR.mkdir(parents=True, exist_ok=True)

    # If no images requested, just write merged markdown
    if not image_specs:
        output_path = BLOG_DIR / f"{plan.blog_title}.md"
        output_path.write_text(md, encoding="utf-8")
        return {"final": md}

    IMAGES_DIR.mkdir(parents=True, exist_ok=True)

    for spec in image_specs:
        placeholder = spec.get("placeholder", "")
        filename = spec.get("filename")
        if not filename:
            continue

        out_path = IMAGES_DIR / filename

        # generate only if needed
        if not out_path.exists():
            try:
                img_bytes = _gemini_generate_image_bytes(spec.get("prompt", ""))
                out_path.write_bytes(img_bytes)
            except Exception as e:
                prompt_block = (
                    f"> **[IMAGE GENERATION FAILED]** {spec.get('caption', '')}\n>\n"
                    f"> **Alt:** {spec.get('alt', '')}\n>\n"
                    f"> **Prompt:** {spec.get('prompt', '')}\n>\n"
                    f"> **Error:** {e}\n"
                )
                md = md.replace(placeholder, prompt_block)
                continue

        # Runs for both freshly-generated AND already-cached images
        img_md = f"![{spec.get('alt', '')}](images/{filename})\n*{spec.get('caption', '')}*"
        md = md.replace(placeholder, img_md)

    output_path = BLOG_DIR / f"{plan.blog_title}.md"
    output_path.write_text(md, encoding="utf-8")
    return {"final": md}